model_parameters:
	onnx_model: 'best.onnx'								#训练完成的模型
	march: 'bayes-e'									    #BPU硬件架构
	output_model_file_prefix: 'best'			#输出文件'best.bin'
	working_dir: './model_output'					#输出目录

input_parameters:										
	input_name: 'images'								  #输入节点名称（默认为'images'）
	input_shape: '1x3x736x736'						#输入现状
	input_layout_train: 'NCHW'						#数据排布格式
	input_type_train: 'bgr'								#图像颜色通道顺序
	input_type_rt: 'nv12'								  #摄像头输入数据格式，BPU可以直接处理nv12
	norm_type: 'data_scale'								#归一化方式
	scale_value: 0.003921568627451				#归一化系数(1/255)

calibration_parameters:									
	cal_data_dir: '../workspace/my_workspace/picture'	#存放图片目录
  preprocess_on: True									  #预处理（否则需要已处理好的bin文件）
  cal_data_type: 'float32'							#校准数据类型

compiler_parameters:
	optimize_level: 'O3'								  #BPU编译优化等级